// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics.sql

package db

import (
	"context"
)

const getAllStatusCounts = `-- name: GetAllStatusCounts :one
SELECT
  COUNT(CASE WHEN status = 'new'         THEN 1 END) AS new_count,
  COUNT(CASE WHEN status = 'in_progress' THEN 1 END) AS in_progress_count,
  COUNT(CASE WHEN status = 'waiting'     THEN 1 END) AS waiting_count,
  COUNT(CASE WHEN status = 'done'        THEN 1 END) AS done_count
FROM tickets
`

type GetAllStatusCountsRow struct {
	NewCount        int64 `db:"new_count" json:"new_count"`
	InProgressCount int64 `db:"in_progress_count" json:"in_progress_count"`
	WaitingCount    int64 `db:"waiting_count" json:"waiting_count"`
	DoneCount       int64 `db:"done_count" json:"done_count"`
}

func (q *Queries) GetAllStatusCounts(ctx context.Context) (GetAllStatusCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getAllStatusCounts)
	var i GetAllStatusCountsRow
	err := row.Scan(
		&i.NewCount,
		&i.InProgressCount,
		&i.WaitingCount,
		&i.DoneCount,
	)
	return i, err
}

const getCustomerAllStatusCounts = `-- name: GetCustomerAllStatusCounts :one
SELECT
  COUNT(CASE WHEN status = 'new'         THEN 1 END) AS new_count,
  COUNT(CASE WHEN status = 'in_progress' THEN 1 END) AS in_progress_count,
  COUNT(CASE WHEN status = 'waiting'     THEN 1 END) AS waiting_count,
  COUNT(CASE WHEN status = 'done'        THEN 1 END) AS done_count
FROM tickets
WHERE customer_id = ?
`

type GetCustomerAllStatusCountsRow struct {
	NewCount        int64 `db:"new_count" json:"new_count"`
	InProgressCount int64 `db:"in_progress_count" json:"in_progress_count"`
	WaitingCount    int64 `db:"waiting_count" json:"waiting_count"`
	DoneCount       int64 `db:"done_count" json:"done_count"`
}

func (q *Queries) GetCustomerAllStatusCounts(ctx context.Context, customerID int64) (GetCustomerAllStatusCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerAllStatusCounts, customerID)
	var i GetCustomerAllStatusCountsRow
	err := row.Scan(
		&i.NewCount,
		&i.InProgressCount,
		&i.WaitingCount,
		&i.DoneCount,
	)
	return i, err
}

const getCustomerMonthlyTrend = `-- name: GetCustomerMonthlyTrend :many
SELECT DATE_FORMAT(received_at, '%Y-%m') AS month, COUNT(*) AS count
FROM tickets
WHERE customer_id = ?
  AND received_at >= DATE_SUB(DATE_FORMAT(NOW(), '%Y-%m-01'), INTERVAL 5 MONTH)
GROUP BY DATE_FORMAT(received_at, '%Y-%m')
ORDER BY month ASC
`

type GetCustomerMonthlyTrendRow struct {
	Month string `db:"month" json:"month"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) GetCustomerMonthlyTrend(ctx context.Context, customerID int64) ([]GetCustomerMonthlyTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerMonthlyTrend, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerMonthlyTrendRow
	for rows.Next() {
		var i GetCustomerMonthlyTrendRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerOpenTypeBreakdown = `-- name: GetCustomerOpenTypeBreakdown :many
SELECT type, COUNT(*) AS count
FROM tickets
WHERE customer_id = ? AND status != 'done'
GROUP BY type
`

type GetCustomerOpenTypeBreakdownRow struct {
	Type  TicketsType `db:"type" json:"type"`
	Count int64       `db:"count" json:"count"`
}

func (q *Queries) GetCustomerOpenTypeBreakdown(ctx context.Context, customerID int64) ([]GetCustomerOpenTypeBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerOpenTypeBreakdown, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerOpenTypeBreakdownRow
	for rows.Next() {
		var i GetCustomerOpenTypeBreakdownRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerSystemsBreakdown = `-- name: GetCustomerSystemsBreakdown :many
SELECT t.system_id, s.name AS system_name,
       COUNT(CASE WHEN t.status = 'new'         THEN 1 END) AS new_count,
       COUNT(CASE WHEN t.status = 'in_progress' THEN 1 END) AS in_progress_count,
       COUNT(CASE WHEN t.status = 'waiting'     THEN 1 END) AS waiting_count,
       COUNT(CASE WHEN t.status = 'done'        THEN 1 END) AS done_count,
       COUNT(*) AS total
FROM tickets t
JOIN systems s ON s.id = t.system_id
WHERE t.customer_id = ?
GROUP BY t.system_id, s.name
ORDER BY total DESC
`

type GetCustomerSystemsBreakdownRow struct {
	SystemID        int64  `db:"system_id" json:"system_id"`
	SystemName      string `db:"system_name" json:"system_name"`
	NewCount        int64  `db:"new_count" json:"new_count"`
	InProgressCount int64  `db:"in_progress_count" json:"in_progress_count"`
	WaitingCount    int64  `db:"waiting_count" json:"waiting_count"`
	DoneCount       int64  `db:"done_count" json:"done_count"`
	Total           int64  `db:"total" json:"total"`
}

func (q *Queries) GetCustomerSystemsBreakdown(ctx context.Context, customerID int64) ([]GetCustomerSystemsBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerSystemsBreakdown, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerSystemsBreakdownRow
	for rows.Next() {
		var i GetCustomerSystemsBreakdownRow
		if err := rows.Scan(
			&i.SystemID,
			&i.SystemName,
			&i.NewCount,
			&i.InProgressCount,
			&i.WaitingCount,
			&i.DoneCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrend = `-- name: GetMonthlyTrend :many
SELECT DATE_FORMAT(received_at, '%Y-%m') AS month, COUNT(*) AS count
FROM tickets
WHERE received_at >= DATE_SUB(DATE_FORMAT(NOW(), '%Y-%m-01'), INTERVAL 5 MONTH)
GROUP BY DATE_FORMAT(received_at, '%Y-%m')
ORDER BY month ASC
`

type GetMonthlyTrendRow struct {
	Month string `db:"month" json:"month"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) GetMonthlyTrend(ctx context.Context) ([]GetMonthlyTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTrendRow
	for rows.Next() {
		var i GetMonthlyTrendRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenPriorityBreakdown = `-- name: GetOpenPriorityBreakdown :many
SELECT priority, COUNT(*) AS count
FROM tickets
WHERE status != 'done'
GROUP BY priority
`

type GetOpenPriorityBreakdownRow struct {
	Priority TicketsPriority `db:"priority" json:"priority"`
	Count    int64           `db:"count" json:"count"`
}

func (q *Queries) GetOpenPriorityBreakdown(ctx context.Context) ([]GetOpenPriorityBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getOpenPriorityBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpenPriorityBreakdownRow
	for rows.Next() {
		var i GetOpenPriorityBreakdownRow
		if err := rows.Scan(&i.Priority, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenTypeBreakdown = `-- name: GetOpenTypeBreakdown :many
SELECT type, COUNT(*) AS count
FROM tickets
WHERE status != 'done'
GROUP BY type
`

type GetOpenTypeBreakdownRow struct {
	Type  TicketsType `db:"type" json:"type"`
	Count int64       `db:"count" json:"count"`
}

func (q *Queries) GetOpenTypeBreakdown(ctx context.Context) ([]GetOpenTypeBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getOpenTypeBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpenTypeBreakdownRow
	for rows.Next() {
		var i GetOpenTypeBreakdownRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSystemsByOpenCount = `-- name: GetTopSystemsByOpenCount :many
SELECT t.system_id, s.name AS system_name, COUNT(*) AS count
FROM tickets t
JOIN systems s ON s.id = t.system_id
WHERE t.status IN ('new', 'in_progress', 'waiting')
GROUP BY t.system_id, s.name
ORDER BY count DESC
LIMIT 6
`

type GetTopSystemsByOpenCountRow struct {
	SystemID   int64  `db:"system_id" json:"system_id"`
	SystemName string `db:"system_name" json:"system_name"`
	Count      int64  `db:"count" json:"count"`
}

func (q *Queries) GetTopSystemsByOpenCount(ctx context.Context) ([]GetTopSystemsByOpenCountRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopSystemsByOpenCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSystemsByOpenCountRow
	for rows.Next() {
		var i GetTopSystemsByOpenCountRow
		if err := rows.Scan(&i.SystemID, &i.SystemName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
