// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attachments.sql

package db

import (
	"context"
	"database/sql"
)

const createAttachment = `-- name: CreateAttachment :execresult
INSERT INTO attachments (ticket_id, uploaded_by, file_name, file_key, file_size, content_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	TicketID    int64  `db:"ticket_id" json:"ticket_id"`
	UploadedBy  int64  `db:"uploaded_by" json:"uploaded_by"`
	FileName    string `db:"file_name" json:"file_name"`
	FileKey     string `db:"file_key" json:"file_key"`
	FileSize    int32  `db:"file_size" json:"file_size"`
	ContentType string `db:"content_type" json:"content_type"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAttachment,
		arg.TicketID,
		arg.UploadedBy,
		arg.FileName,
		arg.FileKey,
		arg.FileSize,
		arg.ContentType,
	)
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ? AND ticket_id = ?
`

type DeleteAttachmentParams struct {
	ID       int64 `db:"id" json:"id"`
	TicketID int64 `db:"ticket_id" json:"ticket_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.TicketID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, ticket_id, uploaded_by, file_name, file_key, file_size, content_type, created_at
FROM attachments
WHERE id = ? AND ticket_id = ? LIMIT 1
`

type GetAttachmentParams struct {
	ID       int64 `db:"id" json:"id"`
	TicketID int64 `db:"ticket_id" json:"ticket_id"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, arg.ID, arg.TicketID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UploadedBy,
		&i.FileName,
		&i.FileKey,
		&i.FileSize,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, ticket_id, uploaded_by, file_name, file_key, file_size, content_type, created_at
FROM attachments
WHERE ticket_id = ?
`

func (q *Queries) ListAttachments(ctx context.Context, ticketID int64) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UploadedBy,
			&i.FileName,
			&i.FileKey,
			&i.FileSize,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
