// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :execresult
INSERT INTO comments (ticket_id, author_id, body) VALUES (?, ?, ?)
`

type CreateCommentParams struct {
	TicketID int64  `db:"ticket_id" json:"ticket_id"`
	AuthorID int64  `db:"author_id" json:"author_id"`
	Body     string `db:"body" json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createComment, arg.TicketID, arg.AuthorID, arg.Body)
}

const listComments = `-- name: ListComments :many
SELECT id, ticket_id, author_id, body, created_at
FROM comments
WHERE ticket_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListComments(ctx context.Context, ticketID int64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
