// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customers.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customers (name, notes, is_active)
VALUES (?, ?, ?)
`

type CreateCustomerParams struct {
	Name     string         `db:"name" json:"name"`
	Notes    sql.NullString `db:"notes" json:"notes"`
	IsActive bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer, arg.Name, arg.Notes, arg.IsActive)
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, notes, is_active, created_at, updated_at
FROM customers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomersActive = `-- name: ListCustomersActive :many
SELECT id, name, notes, is_active, created_at, updated_at
FROM customers
WHERE is_active = TRUE
ORDER BY name
`

func (q *Queries) ListCustomersActive(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersAll = `-- name: ListCustomersAll :many
SELECT id, name, notes, is_active, created_at, updated_at
FROM customers
ORDER BY name
`

func (q *Queries) ListCustomersAll(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET name = ?, notes = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCustomerParams struct {
	Name     string         `db:"name" json:"name"`
	Notes    sql.NullString `db:"notes" json:"notes"`
	IsActive bool           `db:"is_active" json:"is_active"`
	ID       int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer,
		arg.Name,
		arg.Notes,
		arg.IsActive,
		arg.ID,
	)
	return err
}
