// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type TicketsPriority string

const (
	TicketsPriorityHigh   TicketsPriority = "high"
	TicketsPriorityMedium TicketsPriority = "medium"
	TicketsPriorityLow    TicketsPriority = "low"
)

func (e *TicketsPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsPriority(s)
	case string:
		*e = TicketsPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsPriority: %T", src)
	}
	return nil
}

type NullTicketsPriority struct {
	TicketsPriority TicketsPriority `json:"tickets_priority"`
	Valid           bool            `json:"valid"` // Valid is true if TicketsPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsPriority), nil
}

type TicketsStatus string

const (
	TicketsStatusNew        TicketsStatus = "new"
	TicketsStatusInProgress TicketsStatus = "in_progress"
	TicketsStatusWaiting    TicketsStatus = "waiting"
	TicketsStatusDone       TicketsStatus = "done"
)

func (e *TicketsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsStatus(s)
	case string:
		*e = TicketsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsStatus: %T", src)
	}
	return nil
}

type NullTicketsStatus struct {
	TicketsStatus TicketsStatus `json:"tickets_status"`
	Valid         bool          `json:"valid"` // Valid is true if TicketsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsStatus), nil
}

type TicketsType string

const (
	TicketsTypeQuestion TicketsType = "question"
	TicketsTypeBug      TicketsType = "bug"
	TicketsTypeConfig   TicketsType = "config"
	TicketsTypeData     TicketsType = "data"
)

func (e *TicketsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsType(s)
	case string:
		*e = TicketsType(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsType: %T", src)
	}
	return nil
}

type NullTicketsType struct {
	TicketsType TicketsType `json:"tickets_type"`
	Valid       bool        `json:"valid"` // Valid is true if TicketsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsType) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsType), nil
}

type UsersRole string

const (
	UsersRoleAdmin  UsersRole = "admin"
	UsersRoleMember UsersRole = "member"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type Attachment struct {
	ID          int64     `db:"id" json:"id"`
	TicketID    int64     `db:"ticket_id" json:"ticket_id"`
	UploadedBy  int64     `db:"uploaded_by" json:"uploaded_by"`
	FileName    string    `db:"file_name" json:"file_name"`
	FileKey     string    `db:"file_key" json:"file_key"`
	FileSize    int32     `db:"file_size" json:"file_size"`
	ContentType string    `db:"content_type" json:"content_type"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type Comment struct {
	ID        int64     `db:"id" json:"id"`
	TicketID  int64     `db:"ticket_id" json:"ticket_id"`
	AuthorID  int64     `db:"author_id" json:"author_id"`
	Body      string    `db:"body" json:"body"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Customer struct {
	ID        int64          `db:"id" json:"id"`
	Name      string         `db:"name" json:"name"`
	Notes     sql.NullString `db:"notes" json:"notes"`
	IsActive  bool           `db:"is_active" json:"is_active"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt time.Time      `db:"updated_at" json:"updated_at"`
}

type System struct {
	ID          int64          `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	CustomerID  int64          `db:"customer_id" json:"customer_id"`
	Description sql.NullString `db:"description" json:"description"`
	IsActive    bool           `db:"is_active" json:"is_active"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type SystemAssignee struct {
	SystemID int64 `db:"system_id" json:"system_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

type Ticket struct {
	ID          int64           `db:"id" json:"id"`
	Title       string          `db:"title" json:"title"`
	Description sql.NullString  `db:"description" json:"description"`
	Type        TicketsType     `db:"type" json:"type"`
	Priority    TicketsPriority `db:"priority" json:"priority"`
	Status      TicketsStatus   `db:"status" json:"status"`
	CustomerID  int64           `db:"customer_id" json:"customer_id"`
	SystemID    int64           `db:"system_id" json:"system_id"`
	AssigneeID  sql.NullInt64   `db:"assignee_id" json:"assignee_id"`
	CreatedBy   int64           `db:"created_by" json:"created_by"`
	ReceivedAt  time.Time       `db:"received_at" json:"received_at"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}

type TicketHistory struct {
	ID        int64          `db:"id" json:"id"`
	TicketID  int64          `db:"ticket_id" json:"ticket_id"`
	ChangedBy int64          `db:"changed_by" json:"changed_by"`
	FieldName string         `db:"field_name" json:"field_name"`
	OldValue  sql.NullString `db:"old_value" json:"old_value"`
	NewValue  sql.NullString `db:"new_value" json:"new_value"`
	ChangedAt time.Time      `db:"changed_at" json:"changed_at"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	Role         UsersRole `db:"role" json:"role"`
	IsActive     bool      `db:"is_active" json:"is_active"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
