// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: systems.sql

package db

import (
	"context"
	"database/sql"
)

const createSystem = `-- name: CreateSystem :execresult
INSERT INTO systems (name, customer_id, description, is_active)
VALUES (?, ?, ?, ?)
`

type CreateSystemParams struct {
	Name        string         `db:"name" json:"name"`
	CustomerID  int64          `db:"customer_id" json:"customer_id"`
	Description sql.NullString `db:"description" json:"description"`
	IsActive    bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateSystem(ctx context.Context, arg CreateSystemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSystem,
		arg.Name,
		arg.CustomerID,
		arg.Description,
		arg.IsActive,
	)
}

const getSystem = `-- name: GetSystem :one
SELECT id, name, customer_id, description, is_active, created_at, updated_at
FROM systems
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSystem(ctx context.Context, id int64) (System, error) {
	row := q.db.QueryRowContext(ctx, getSystem, id)
	var i System
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerID,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemsActive = `-- name: ListSystemsActive :many
SELECT id, name, customer_id, description, is_active, created_at, updated_at
FROM systems
WHERE is_active = TRUE
ORDER BY name
`

func (q *Queries) ListSystemsActive(ctx context.Context) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystemsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemsActiveByCustomer = `-- name: ListSystemsActiveByCustomer :many
SELECT id, name, customer_id, description, is_active, created_at, updated_at
FROM systems
WHERE customer_id = ? AND is_active = TRUE
ORDER BY name
`

func (q *Queries) ListSystemsActiveByCustomer(ctx context.Context, customerID int64) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystemsActiveByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemsAll = `-- name: ListSystemsAll :many
SELECT id, name, customer_id, description, is_active, created_at, updated_at
FROM systems
ORDER BY name
`

func (q *Queries) ListSystemsAll(ctx context.Context) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystemsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemsByCustomer = `-- name: ListSystemsByCustomer :many
SELECT id, name, customer_id, description, is_active, created_at, updated_at
FROM systems
WHERE customer_id = ?
ORDER BY name
`

func (q *Queries) ListSystemsByCustomer(ctx context.Context, customerID int64) ([]System, error) {
	rows, err := q.db.QueryContext(ctx, listSystemsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []System
	for rows.Next() {
		var i System
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CustomerID,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystem = `-- name: UpdateSystem :exec
UPDATE systems
SET name = ?, description = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSystemParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	IsActive    bool           `db:"is_active" json:"is_active"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateSystem(ctx context.Context, arg UpdateSystemParams) error {
	_, err := q.db.ExecContext(ctx, updateSystem,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	return err
}
