// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: system_assignees.sql

package db

import (
	"context"
)

const createSystemAssignee = `-- name: CreateSystemAssignee :exec
INSERT INTO system_assignees (system_id, user_id) VALUES (?, ?)
`

type CreateSystemAssigneeParams struct {
	SystemID int64 `db:"system_id" json:"system_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) CreateSystemAssignee(ctx context.Context, arg CreateSystemAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, createSystemAssignee, arg.SystemID, arg.UserID)
	return err
}

const deleteSystemAssignees = `-- name: DeleteSystemAssignees :exec
DELETE FROM system_assignees WHERE system_id = ?
`

func (q *Queries) DeleteSystemAssignees(ctx context.Context, systemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSystemAssignees, systemID)
	return err
}

const listSystemAssignees = `-- name: ListSystemAssignees :many
SELECT system_id, user_id
FROM system_assignees
WHERE system_id = ?
`

func (q *Queries) ListSystemAssignees(ctx context.Context, systemID int64) ([]SystemAssignee, error) {
	rows, err := q.db.QueryContext(ctx, listSystemAssignees, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemAssignee
	for rows.Next() {
		var i SystemAssignee
		if err := rows.Scan(&i.SystemID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
