// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ticket_history.sql

package db

import (
	"context"
	"database/sql"
)

const createTicketHistory = `-- name: CreateTicketHistory :exec
INSERT INTO ticket_history (ticket_id, changed_by, field_name, old_value, new_value)
VALUES (?, ?, ?, ?, ?)
`

type CreateTicketHistoryParams struct {
	TicketID  int64          `db:"ticket_id" json:"ticket_id"`
	ChangedBy int64          `db:"changed_by" json:"changed_by"`
	FieldName string         `db:"field_name" json:"field_name"`
	OldValue  sql.NullString `db:"old_value" json:"old_value"`
	NewValue  sql.NullString `db:"new_value" json:"new_value"`
}

func (q *Queries) CreateTicketHistory(ctx context.Context, arg CreateTicketHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createTicketHistory,
		arg.TicketID,
		arg.ChangedBy,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listTicketHistory = `-- name: ListTicketHistory :many
SELECT id, ticket_id, changed_by, field_name, old_value, new_value, changed_at
FROM ticket_history
WHERE ticket_id = ?
ORDER BY changed_at ASC
`

func (q *Queries) ListTicketHistory(ctx context.Context, ticketID int64) ([]TicketHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTicketHistory, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketHistory
	for rows.Next() {
		var i TicketHistory
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ChangedBy,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
