// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tickets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countOpenTicketsBySystem = `-- name: CountOpenTicketsBySystem :one
SELECT COUNT(*) FROM tickets
WHERE system_id = ? AND status IN ('new', 'in_progress', 'waiting')
`

func (q *Queries) CountOpenTicketsBySystem(ctx context.Context, systemID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenTicketsBySystem, systemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsByStatus = `-- name: CountTicketsByStatus :one
SELECT COUNT(*) FROM tickets WHERE status = ?
`

func (q *Queries) CountTicketsByStatus(ctx context.Context, status TicketsStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :execresult
INSERT INTO tickets (title, description, type, priority, status,
                     customer_id, system_id, assignee_id, created_by, received_at)
VALUES (?, ?, ?, ?, 'new', ?, ?, ?, ?, ?)
`

type CreateTicketParams struct {
	Title       string          `db:"title" json:"title"`
	Description sql.NullString  `db:"description" json:"description"`
	Type        TicketsType     `db:"type" json:"type"`
	Priority    TicketsPriority `db:"priority" json:"priority"`
	CustomerID  int64           `db:"customer_id" json:"customer_id"`
	SystemID    int64           `db:"system_id" json:"system_id"`
	AssigneeID  sql.NullInt64   `db:"assignee_id" json:"assignee_id"`
	CreatedBy   int64           `db:"created_by" json:"created_by"`
	ReceivedAt  time.Time       `db:"received_at" json:"received_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTicket,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Priority,
		arg.CustomerID,
		arg.SystemID,
		arg.AssigneeID,
		arg.CreatedBy,
		arg.ReceivedAt,
	)
}

const getTicket = `-- name: GetTicket :one
SELECT id, title, description, type, priority, status,
       customer_id, system_id, assignee_id, created_by,
       received_at, created_at, updated_at
FROM tickets
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Priority,
		&i.Status,
		&i.CustomerID,
		&i.SystemID,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketDetail = `-- name: GetTicketDetail :one
SELECT t.id, t.title, t.description, t.type, t.priority, t.status,
       t.customer_id, c.name AS customer_name,
       t.system_id,   s.name AS system_name,
       t.assignee_id, a.name AS assignee_name,
       t.created_by,  cb.name AS created_by_name,
       t.received_at, t.created_at, t.updated_at
FROM tickets t
JOIN customers c  ON c.id = t.customer_id
JOIN systems   s  ON s.id = t.system_id
LEFT JOIN users a ON a.id = t.assignee_id
JOIN users     cb ON cb.id = t.created_by
WHERE t.id = ? LIMIT 1
`

type GetTicketDetailRow struct {
	ID            int64           `db:"id" json:"id"`
	Title         string          `db:"title" json:"title"`
	Description   sql.NullString  `db:"description" json:"description"`
	Type          TicketsType     `db:"type" json:"type"`
	Priority      TicketsPriority `db:"priority" json:"priority"`
	Status        TicketsStatus   `db:"status" json:"status"`
	CustomerID    int64           `db:"customer_id" json:"customer_id"`
	CustomerName  string          `db:"customer_name" json:"customer_name"`
	SystemID      int64           `db:"system_id" json:"system_id"`
	SystemName    string          `db:"system_name" json:"system_name"`
	AssigneeID    sql.NullInt64   `db:"assignee_id" json:"assignee_id"`
	AssigneeName  sql.NullString  `db:"assignee_name" json:"assignee_name"`
	CreatedBy     int64           `db:"created_by" json:"created_by"`
	CreatedByName string          `db:"created_by_name" json:"created_by_name"`
	ReceivedAt    time.Time       `db:"received_at" json:"received_at"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTicketDetail(ctx context.Context, id int64) (GetTicketDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketDetail, id)
	var i GetTicketDetailRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Priority,
		&i.Status,
		&i.CustomerID,
		&i.CustomerName,
		&i.SystemID,
		&i.SystemName,
		&i.AssigneeID,
		&i.AssigneeName,
		&i.CreatedBy,
		&i.CreatedByName,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, title, description, type, priority, status,
       customer_id, system_id, assignee_id, created_by,
       received_at, created_at, updated_at
FROM tickets
ORDER BY received_at DESC
`

func (q *Queries) ListTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.Status,
			&i.CustomerID,
			&i.SystemID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByStatus = `-- name: ListTicketsByStatus :many
SELECT id, title, description, type, priority, status,
       customer_id, system_id, assignee_id, created_by,
       received_at, created_at, updated_at
FROM tickets
WHERE status = ?
ORDER BY received_at DESC
`

func (q *Queries) ListTicketsByStatus(ctx context.Context, status TicketsStatus) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Priority,
			&i.Status,
			&i.CustomerID,
			&i.SystemID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE tickets
SET title = ?, description = ?, type = ?, priority = ?,
    assignee_id = ?, received_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTicketParams struct {
	Title       string          `db:"title" json:"title"`
	Description sql.NullString  `db:"description" json:"description"`
	Type        TicketsType     `db:"type" json:"type"`
	Priority    TicketsPriority `db:"priority" json:"priority"`
	AssigneeID  sql.NullInt64   `db:"assignee_id" json:"assignee_id"`
	ReceivedAt  time.Time       `db:"received_at" json:"received_at"`
	ID          int64           `db:"id" json:"id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.ExecContext(ctx, updateTicket,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Priority,
		arg.AssigneeID,
		arg.ReceivedAt,
		arg.ID,
	)
	return err
}

const updateTicketAssignee = `-- name: UpdateTicketAssignee :exec
UPDATE tickets SET assignee_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTicketAssigneeParams struct {
	AssigneeID sql.NullInt64 `db:"assignee_id" json:"assignee_id"`
	ID         int64         `db:"id" json:"id"`
}

func (q *Queries) UpdateTicketAssignee(ctx context.Context, arg UpdateTicketAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketAssignee, arg.AssigneeID, arg.ID)
	return err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTicketStatusParams struct {
	Status TicketsStatus `db:"status" json:"status"`
	ID     int64         `db:"id" json:"id"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.ID)
	return err
}
