run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - gosec
    - misspell

linters-settings:
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G104 # errcheck covers this

issues:
  exclude-dirs:
    - internal/apigen
    - internal/db/sqlc
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
