// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apigen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for TicketPriority.
const (
	High   TicketPriority = "high"
	Low    TicketPriority = "low"
	Medium TicketPriority = "medium"
)

// Valid indicates whether the value is a known member of the TicketPriority enum.
func (e TicketPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for TicketStatus.
const (
	Done       TicketStatus = "done"
	InProgress TicketStatus = "in_progress"
	New        TicketStatus = "new"
	Waiting    TicketStatus = "waiting"
)

// Valid indicates whether the value is a known member of the TicketStatus enum.
func (e TicketStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case InProgress:
		return true
	case New:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for TicketType.
const (
	Bug      TicketType = "bug"
	Config   TicketType = "config"
	Data     TicketType = "data"
	Question TicketType = "question"
)

// Valid indicates whether the value is a known member of the TicketType enum.
func (e TicketType) Valid() bool {
	switch e {
	case Bug:
		return true
	case Config:
		return true
	case Data:
		return true
	case Question:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin  UserRole = "admin"
	Member UserRole = "member"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType *string    `json:"content_type,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`

	// DownloadUrl 署名付きS3 URL（有効期限: 15分）
	DownloadUrl *string `json:"download_url,omitempty"`
	FileName    *string `json:"file_name,omitempty"`

	// FileSize ファイルサイズ（バイト）
	FileSize       *int    `json:"file_size,omitempty"`
	Id             *int64  `json:"id,omitempty"`
	TicketId       *int64  `json:"ticket_id,omitempty"`
	UploadedBy     *int64  `json:"uploaded_by,omitempty"`
	UploadedByName *string `json:"uploaded_by_name,omitempty"`
}

// Comment defines model for Comment.
type Comment struct {
	AuthorId   *int64     `json:"author_id,omitempty"`
	AuthorName *string    `json:"author_name,omitempty"`
	Body       *string    `json:"body,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *int64     `json:"id,omitempty"`
	TicketId   *int64     `json:"ticket_id,omitempty"`
}

// Customer defines model for Customer.
type Customer struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	IsActive  *bool      `json:"is_active,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Notes     *string    `json:"notes,omitempty"`

	// SystemCount 紐づくシステム総数（有効・無効含む）。DBカラムではなく SELECT COUNT(*) で動的に計算される。
	SystemCount *int `json:"system_count,omitempty"`

	// Systems include=systems 指定時のみ返す
	Systems   *[]SystemSummary `json:"systems,omitempty"`
	UpdatedAt *time.Time       `json:"updated_at,omitempty"`
}

// CustomerCreate defines model for CustomerCreate.
type CustomerCreate struct {
	IsActive *bool   `json:"is_active,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`
}

// CustomerReport defines model for CustomerReport.
type CustomerReport struct {
	CountsByStatus *StatusCounts `json:"counts_by_status,omitempty"`
	CustomerId     *int64        `json:"customer_id,omitempty"`
	CustomerName   *string       `json:"customer_name,omitempty"`

	// MonthlyTrend 過去6ヶ月の月次件数・当月含む（古い順）。集計基準は received_at
	MonthlyTrend     *[]MonthlyTrendItem `json:"monthly_trend,omitempty"`
	OpenCountsByType *TypeCounts         `json:"open_counts_by_type,omitempty"`

	// SystemBreakdown システム別ステータス件数
	SystemBreakdown *[]struct {
		Counts     *StatusCounts `json:"counts,omitempty"`
		SystemId   *int64        `json:"system_id,omitempty"`
		SystemName *string       `json:"system_name,omitempty"`
		Total      *int          `json:"total,omitempty"`
	} `json:"system_breakdown,omitempty"`
}

// CustomerUpdate defines model for CustomerUpdate.
type CustomerUpdate struct {
	IsActive *bool   `json:"is_active,omitempty"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`
}

// DashboardSummary defines model for DashboardSummary.
type DashboardSummary struct {
	CountsByStatus *StatusCounts `json:"counts_by_status,omitempty"`

	// MonthlyTrend 過去6ヶ月の月次件数・当月含む（古い順）。集計基準は received_at
	MonthlyTrend         *[]MonthlyTrendItem `json:"monthly_trend,omitempty"`
	OpenCountsByPriority *PriorityCounts     `json:"open_counts_by_priority,omitempty"`
	OpenCountsByType     *TypeCounts         `json:"open_counts_by_type,omitempty"`

	// TopSystemsByOpenCount 未完了件数上位6システム
	TopSystemsByOpenCount *[]struct {
		Count      *int    `json:"count,omitempty"`
		SystemId   *int64  `json:"system_id,omitempty"`
		SystemName *string `json:"system_name,omitempty"`
	} `json:"top_systems_by_open_count,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code エラーコード（スネークケースの大文字）
	Code string `json:"code"`

	// Details フィールドごとのバリデーションエラー詳細。キーはフィールド名、値は日本語エラーメッセージ
	Details *map[string]string `json:"details,omitempty"`

	// Message ユーザー向けエラーメッセージ（日本語）
	Message string `json:"message"`
}

// MonthlyTrendItem defines model for MonthlyTrendItem.
type MonthlyTrendItem struct {
	Count *int `json:"count,omitempty"`

	// Month YYYY-MM 形式
	Month *string `json:"month,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page 現在ページ
	Page *int `json:"page,omitempty"`

	// PerPage 1ページあたりの件数
	PerPage *int `json:"per_page,omitempty"`

	// Total 総件数
	Total *int `json:"total,omitempty"`

	// TotalPages 総ページ数
	TotalPages *int `json:"total_pages,omitempty"`
}

// PriorityCounts defines model for PriorityCounts.
type PriorityCounts struct {
	High   *int `json:"high,omitempty"`
	Low    *int `json:"low,omitempty"`
	Medium *int `json:"medium,omitempty"`
}

// SidebarData defines model for SidebarData.
type SidebarData struct {
	Customers *[]struct {
		Id      *int64  `json:"id,omitempty"`
		Name    *string `json:"name,omitempty"`
		Systems *[]struct {
			Id   *int64  `json:"id,omitempty"`
			Name *string `json:"name,omitempty"`

			// OpenTicketCount 未完了チケット件数（status が new / in_progress / waiting の合計）
			OpenTicketCount *int `json:"open_ticket_count,omitempty"`
		} `json:"systems,omitempty"`
	} `json:"customers,omitempty"`
}

// StatusCounts defines model for StatusCounts.
type StatusCounts struct {
	Done       *int `json:"done,omitempty"`
	InProgress *int `json:"in_progress,omitempty"`
	New        *int `json:"new,omitempty"`
	Waiting    *int `json:"waiting,omitempty"`
}

// System defines model for System.
type System struct {
	// Assignees `GET /systems?include=assignees` または `GET /systems/{id}` の場合のみ返す。省略時は空配列。
	Assignees    *[]UserSummary `json:"assignees,omitempty"`
	CreatedAt    *time.Time     `json:"created_at,omitempty"`
	CustomerId   *int64         `json:"customer_id,omitempty"`
	CustomerName *string        `json:"customer_name,omitempty"`
	Description  *string        `json:"description,omitempty"`
	Id           *int64         `json:"id,omitempty"`
	IsActive     *bool          `json:"is_active,omitempty"`
	Name         *string        `json:"name,omitempty"`
	UpdatedAt    *time.Time     `json:"updated_at,omitempty"`
}

// SystemCreate defines model for SystemCreate.
type SystemCreate struct {
	AssigneeUserIds *[]int64 `json:"assignee_user_ids,omitempty"`
	CustomerId      int64    `json:"customer_id"`
	Description     *string  `json:"description,omitempty"`
	IsActive        *bool    `json:"is_active,omitempty"`
	Name            string   `json:"name"`
}

// SystemDashboard defines model for SystemDashboard.
type SystemDashboard struct {
	CountsByStatus *StatusCounts `json:"counts_by_status,omitempty"`
	CustomerId     *int64        `json:"customer_id,omitempty"`
	CustomerName   *string       `json:"customer_name,omitempty"`
	SystemId       *int64        `json:"system_id,omitempty"`
	SystemName     *string       `json:"system_name,omitempty"`
}

// SystemSummary サイドバー・選択肢表示用の軽量システム情報
type SystemSummary struct {
	Id       *int64  `json:"id,omitempty"`
	IsActive *bool   `json:"is_active,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// SystemUpdate defines model for SystemUpdate.
type SystemUpdate struct {
	AssigneeUserIds *[]int64 `json:"assignee_user_ids,omitempty"`
	Description     *string  `json:"description,omitempty"`
	IsActive        *bool    `json:"is_active,omitempty"`
	Name            string   `json:"name"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	AssigneeId    *int64     `json:"assignee_id,omitempty"`
	AssigneeName  *string    `json:"assignee_name,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	CreatedBy     *int64     `json:"created_by,omitempty"`
	CreatedByName *string    `json:"created_by_name,omitempty"`
	CustomerId    *int64     `json:"customer_id,omitempty"`
	CustomerName  *string    `json:"customer_name,omitempty"`
	Description   *string    `json:"description,omitempty"`
	Id            *int64     `json:"id,omitempty"`

	// Priority - high: 高
	// - medium: 中
	// - low: 低
	Priority   *TicketPriority `json:"priority,omitempty"`
	ReceivedAt *time.Time      `json:"received_at,omitempty"`

	// Status - new: 新規受付
	// - in_progress: 対応中
	// - waiting: 確認待ち
	// - done: 完了
	Status     *TicketStatus `json:"status,omitempty"`
	SystemId   *int64        `json:"system_id,omitempty"`
	SystemName *string       `json:"system_name,omitempty"`
	Title      *string       `json:"title,omitempty"`

	// Type - question: 操作方法の質問
	// - bug: バグ報告
	// - config: 設定変更依頼
	// - data: データ修正依頼
	Type      *TicketType `json:"type,omitempty"`
	UpdatedAt *time.Time  `json:"updated_at,omitempty"`
}

// TicketCreate 登録時の初期ステータスは常に `new`（新規受付）。
// リクエストで status を指定することはできない。
type TicketCreate struct {
	AssigneeId  *int64  `json:"assignee_id,omitempty"`
	CustomerId  int64   `json:"customer_id"`
	Description *string `json:"description,omitempty"`

	// Priority - high: 高
	// - medium: 中
	// - low: 低
	Priority TicketPriority `json:"priority"`

	// ReceivedAt 省略時はサーバー現在日時
	ReceivedAt *time.Time `json:"received_at,omitempty"`
	SystemId   int64      `json:"system_id"`
	Title      string     `json:"title"`

	// Type - question: 操作方法の質問
	// - bug: バグ報告
	// - config: 設定変更依頼
	// - data: データ修正依頼
	Type TicketType `json:"type"`
}

// TicketPriority - high: 高
// - medium: 中
// - low: 低
type TicketPriority string

// TicketStatus - new: 新規受付
// - in_progress: 対応中
// - waiting: 確認待ち
// - done: 完了
type TicketStatus string

// TicketType - question: 操作方法の質問
// - bug: バグ報告
// - config: 設定変更依頼
// - data: データ修正依頼
type TicketType string

// TicketUpdate defines model for TicketUpdate.
type TicketUpdate struct {
	AssigneeId  *int64  `json:"assignee_id,omitempty"`
	Description *string `json:"description,omitempty"`

	// Priority - high: 高
	// - medium: 中
	// - low: 低
	Priority   TicketPriority `json:"priority"`
	ReceivedAt *time.Time     `json:"received_at,omitempty"`
	Title      string         `json:"title"`

	// Type - question: 操作方法の質問
	// - bug: バグ報告
	// - config: 設定変更依頼
	// - data: データ修正依頼
	Type TicketType `json:"type"`
}

// TypeCounts defines model for TypeCounts.
type TypeCounts struct {
	Bug      *int `json:"bug,omitempty"`
	Config   *int `json:"config,omitempty"`
	Data     *int `json:"data,omitempty"`
	Question *int `json:"question,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time           `json:"created_at,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	Id        *int64               `json:"id,omitempty"`
	IsActive  *bool                `json:"is_active,omitempty"`
	Name      *string              `json:"name,omitempty"`

	// Role - admin: 管理者（全機能アクセス可）
	// - member: メンバー（チケット操作・閲覧のみ）
	Role      *UserRole  `json:"role,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UserRole - admin: 管理者（全機能アクセス可）
// - member: メンバー（チケット操作・閲覧のみ）
type UserRole string

// UserSummary 選択肢表示用の軽量ユーザー情報
type UserSummary struct {
	Id   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// CustomerId defines model for customerId.
type CustomerId = int64

// SystemId defines model for systemId.
type SystemId = int64

// TicketId defines model for ticketId.
type TicketId = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// GetCustomersParams defines parameters for GetCustomers.
type GetCustomersParams struct {
	// IsActive 有効フラグでフィルタ。省略時は全件返す
	IsActive *bool `form:"is_active,omitempty" json:"is_active,omitempty"`

	// Include 追加取得するリレーション（カンマ区切り）。例: systems
	Include *string `form:"include,omitempty" json:"include,omitempty"`
	Page    *int    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int    `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetSystemsParams defines parameters for GetSystems.
type GetSystemsParams struct {
	// CustomerId 顧客企業IDで絞り込み（チケット登録フォームの連動絞り込み用）
	CustomerId *int64 `form:"customer_id,omitempty" json:"customer_id,omitempty"`
	IsActive   *bool  `form:"is_active,omitempty" json:"is_active,omitempty"`

	// Include 追加取得するリレーション（カンマ区切り）。例: assignees
	Include *string `form:"include,omitempty" json:"include,omitempty"`
	Page    *int    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int    `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PutSystemsSystemIdAssigneesJSONBody defines parameters for PutSystemsSystemIdAssignees.
type PutSystemsSystemIdAssigneesJSONBody struct {
	// UserIds 担当者プールに設定するユーザーIDの全件リスト
	UserIds []int64 `json:"user_ids"`
}

// GetTicketsParams defines parameters for GetTickets.
type GetTicketsParams struct {
	Status     *TicketStatus   `form:"status,omitempty" json:"status,omitempty"`
	Priority   *TicketPriority `form:"priority,omitempty" json:"priority,omitempty"`
	Type       *TicketType     `form:"type,omitempty" json:"type,omitempty"`
	CustomerId *int64          `form:"customer_id,omitempty" json:"customer_id,omitempty"`
	SystemId   *int64          `form:"system_id,omitempty" json:"system_id,omitempty"`

	// Keyword タイトル・詳細内容の部分一致検索
	Keyword *string `form:"keyword,omitempty" json:"keyword,omitempty"`
	Page    *int    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int    `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PatchTicketsTicketIdAssigneeJSONBody defines parameters for PatchTicketsTicketIdAssignee.
type PatchTicketsTicketIdAssigneeJSONBody struct {
	AssigneeId *int64 `json:"assignee_id,omitempty"`
}

// PostTicketsTicketIdAttachmentsMultipartBody defines parameters for PostTicketsTicketIdAttachments.
type PostTicketsTicketIdAttachmentsMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PostTicketsTicketIdCommentsJSONBody defines parameters for PostTicketsTicketIdComments.
type PostTicketsTicketIdCommentsJSONBody struct {
	Body string `json:"body"`
}

// PatchTicketsTicketIdStatusJSONBody defines parameters for PatchTicketsTicketIdStatus.
type PatchTicketsTicketIdStatusJSONBody struct {
	// Status - new: 新規受付
	// - in_progress: 対応中
	// - waiting: 確認待ち
	// - done: 完了
	Status TicketStatus `json:"status"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	IsActive *bool `form:"is_active,omitempty" json:"is_active,omitempty"`
	Page     *int  `form:"page,omitempty" json:"page,omitempty"`
	PerPage  *int  `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// PostCustomersJSONRequestBody defines body for PostCustomers for application/json ContentType.
type PostCustomersJSONRequestBody = CustomerCreate

// PutCustomersCustomerIdJSONRequestBody defines body for PutCustomersCustomerId for application/json ContentType.
type PutCustomersCustomerIdJSONRequestBody = CustomerUpdate

// PostSystemsJSONRequestBody defines body for PostSystems for application/json ContentType.
type PostSystemsJSONRequestBody = SystemCreate

// PutSystemsSystemIdJSONRequestBody defines body for PutSystemsSystemId for application/json ContentType.
type PutSystemsSystemIdJSONRequestBody = SystemUpdate

// PutSystemsSystemIdAssigneesJSONRequestBody defines body for PutSystemsSystemIdAssignees for application/json ContentType.
type PutSystemsSystemIdAssigneesJSONRequestBody PutSystemsSystemIdAssigneesJSONBody

// PostTicketsJSONRequestBody defines body for PostTickets for application/json ContentType.
type PostTicketsJSONRequestBody = TicketCreate

// PutTicketsTicketIdJSONRequestBody defines body for PutTicketsTicketId for application/json ContentType.
type PutTicketsTicketIdJSONRequestBody = TicketUpdate

// PatchTicketsTicketIdAssigneeJSONRequestBody defines body for PatchTicketsTicketIdAssignee for application/json ContentType.
type PatchTicketsTicketIdAssigneeJSONRequestBody PatchTicketsTicketIdAssigneeJSONBody

// PostTicketsTicketIdAttachmentsMultipartRequestBody defines body for PostTicketsTicketIdAttachments for multipart/form-data ContentType.
type PostTicketsTicketIdAttachmentsMultipartRequestBody PostTicketsTicketIdAttachmentsMultipartBody

// PostTicketsTicketIdCommentsJSONRequestBody defines body for PostTicketsTicketIdComments for application/json ContentType.
type PostTicketsTicketIdCommentsJSONRequestBody PostTicketsTicketIdCommentsJSONBody

// PatchTicketsTicketIdStatusJSONRequestBody defines body for PatchTicketsTicketIdStatus for application/json ContentType.
type PatchTicketsTicketIdStatusJSONRequestBody PatchTicketsTicketIdStatusJSONBody
